### ISSUE TITLE
While VM gets long time to boot gets panic when tring to getIpport

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/vertice#274]
Aug 30 09:31:57 megam vertice[25532]: time="2016-08-30T09:31:57Z" level=debug msg="\x1b[1;36;10m\n> args   \x1b[0m [oneadmin:dyovAupAuck9 369]\n"
Aug 30 09:31:57 megam vertice[25532]: time="2016-08-30T09:31:57Z" level=debug msg="\x1b[1;34;10m  > [one-go] ( ´ ▽ ` ) SUCCESS\x1b[0m"
Aug 30 09:31:57 megam vertice[25532]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 30 09:31:57 megam vertice[25532]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x68faa8]
Aug 30 09:31:57 megam vertice[25532]: goroutine 550 [running]:
Aug 30 09:31:57 megam vertice[25532]: panic(0xa9db00, 0xc420010050)
Aug 30 09:31:57 megam vertice[25532]:         /root/software/go/src/runtime/panic.go:500 +0x1a1
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/vertice/provision/one/cluster.(*Cluster).GetIpPort(0xc420208b40, 0xc42052a2a6, 0x3, 0xc4204f22c0, 0x0, 0xc4204f4446, 0x7, 0x0, 0x0, 0xc4205c9230, ...)
Aug 30 09:31:57 megam vertice[25532]:         /root/code/megam/workspace/gitpackager/vertice/build/jessie/vertice/src/github.com/megamsys/vertice/provision/one/cluster/machine.go:128 +0x108
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/vertice/provision/one/machine.(*Machine).VmHostIpPort(0xc4205c9370, 0xc4205c92f8, 0xc420142b90, 0xc4205c9268)
Aug 30 09:31:57 megam vertice[25532]:         /root/code/megam/workspace/gitpackager/vertice/build/jessie/vertice/src/github.com/megamsys/vertice/provision/one/machine/machine.go:113 +0x190
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/vertice/provision/one.glob..func5(0xb49400, 0xc420550380, 0xc420508520, 0x1, 0x1, 0x0, 0xb6b1d2, 0x4, 0xc4202090e0)
Aug 30 09:31:57 megam vertice[25532]:         /root/code/megam/workspace/gitpackager/vertice/build/jessie/vertice/src/github.com/megamsys/vertice/provision/one/actions.go:138 +0x1a8
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc4204f2940, 0xc420508520, 0x1, 0x1, 0xc420142b90, 0x0)
Aug 30 09:31:57 megam vertice[25532]:         /root/.go/src/github.com/megamsys/libgo/action/action.go:147 +0x7de
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/vertice/provision/one.(*oneProvisioner).deployPipeline(0xc42018b0c0, 0xc4203f5860, 0xc420508430, 0xc, 0x1077980, 0xc4204f27c0, 0x0, 0x74, 0x0, 0x0)
Aug 30 09:31:57 megam vertice[25532]:         /root/code/megam/workspace/gitpackager/vertice/build/jessie/vertice/src/github.com/megamsys/vertice/provision/one/provisioner.go:249 +0x3d3
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/vertice/provision/one.(*oneProvisioner).ImageDeploy(0xc42018b0c0, 0xc4203f5860, 0xc420508430, 0xc, 0x1077980, 0xc4204f27c0, 0x2, 0x2, 0xc420185b90, 0x2)
Aug 30 09:31:57 megam vertice[25532]:         /root/code/megam/workspace/gitpackager/vertice/build/jessie/vertice/src/github.com/megamsys/vertice/provision/one/provisioner.go:214 +0x285
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/vertice/carton.deployToProvisioner(0xc42014a140, 0x1077980, 0xc4204f27c0, 0x1077980, 0xc4204f27c0, 0xc41ffe053c, 0xc420185bb0)
Aug 30 09:31:57 megam vertice[25532]:         /root/code/megam/workspace/gitpackager/vertice/build/jessie/vertice/src/github.com/megamsys/vertice/carton/deploy.go:73 +0x2bc
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/vertice/carton.Deploy(0xc42014a140, 0x0, 0x0)
Aug 30 09:31:57 megam vertice[25532]:         /root/code/megam/workspace/gitpackager/vertice/build/jessie/vertice/src/github.com/megamsys/vertice/carton/deploy.go:58 +0x229
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/vertice/carton.(*Carton).Deploy(0xc42022e780, 0x32, 0x0)
Aug 30 09:31:57 megam vertice[25532]:         /root/code/megam/workspace/gitpackager/vertice/build/jessie/vertice/src/github.com/megamsys/vertice/carton/carton.go:82 +0x114
Aug 30 09:31:57 megam vertice[25532]: github.com/megamsys/vertice/carton.CreateProcess.Process(0xc420476940, 0x16, 0xc42014a100, 0x1, 0x1, 0x0, 0x0)
Aug 30 09:31:57 megam vertice[25532]:         /root/code/megam/workspace/gitpackager/vertice/build/jessie/vertice/src/github.com/megamsys/vertice/carton/megd_process.go:37 +0x48

**Comment by vijaykanthm28** [comment]
we have to fix it for RC

**Comment by vijaykanthm28** [comment]
issue fixed
