### ISSUE TITLE
VM deleted while machine deploying gets panic

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/vertice#413]
07 10:06:40 vds0 virtengine[25318]: time="2017-03-07T10:06:40+02:00" level=debug msg="  => step 5: gethost-port action error - VM deleted while machine deploying"
Mar 07 10:06:40 vds0 virtengine[25318]: time="2017-03-07T10:06:40+02:00" level=debug msg="  => step 4: create-machine action"
Mar 07 10:06:40 vds0 virtengine[25318]: panic: interface conversion: action.Result is nil, not machine.Machine
Mar 07 10:06:40 vds0 virtengine[25318]: goroutine 11450 [running]:
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/provision/one.glob..func8(0x0, 0x0, 0xc4209694e0, 0x1, 0x1)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/provision/one/actions.go:164 +0x415
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/libgo/action.(*Pipeline).rollback(0xc420b744e0, 0x4, 0xc4209694e0, 0x1, 0x1)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/libgo/action/action.go:172 +0x2bc
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc420b744e0, 0xc4209694e0, 0x1, 0x1, 0xd, 0xc420188e00)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/libgo/action/action.go:158 +0x6be
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/provision/one.(*oneProvisioner).deployPipeline(0xc420165380, 0xc4200a1400, 0xc420969480, 0xa, 0x1391c20, 0xc420b74460, 0x0, 0x71, 0x0, 0x0)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/provision/one/provisioner.go:267 +0x5e0
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/provision/one.(*oneProvisioner).ImageDeploy(0xc420165380, 0xc4200a1400, 0xc420969480, 0xa, 0x1391c20, 0xc420b74460, 0x2, 0x2, 0x2, 0x2)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/provision/one/provisioner.go:230 +0x273
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/carton.deployToProvisioner(0xc42000e130, 0x1391c20, 0xc420b74460, 0x1391c20, 0xc420b74460, 0xc420b3b040, 0xc421185ae0)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/deploy.go:81 +0x28e
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/carton.Deploy(0xc42000e130, 0x0, 0x0)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/deploy.go:60 +0x200
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/carton.(*Carton).Deploy(0xc420191c00, 0x32, 0x0)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/carton.go:105 +0x10d
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/carton.CreateProcess.Process(0xc4201dcd80, 0x16, 0xc42000e100, 0x1, 0x1, 0x0, 0x0)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/megd_process.go:37 +0x48
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/carton.(*CreateProcess).Process(0xc42116af90, 0xc42000e100, 0x1, 0x1, 0x0, 0x0)
Mar 07 10:06:40 vds0 virtengine[25318]:         <autogenerated>:2 +0x74
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/carton.(*ReqOperator).Accept(0xc4202db760, 0xc421185f20, 0xc42116af90, 0x0)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/req_operator.go:44 +0x15b
Mar 07 10:06:40 vds0 virtengine[25318]: github.com/megamsys/vertice/subd/deployd.(*Handler).serveNSQ(0xc42020dbc0, 0xc420525100, 0x0, 0x0)
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/subd/deployd/handler.go:24 +0x10c
Mar 07 10:06:40 vds0 virtengine[25318]: created by github.com/megamsys/vertice/subd/deployd.(*Service).processNSQ
Mar 07 10:06:40 vds0 virtengine[25318]:         /home/jonathan/.go/src/github.com/megamsys/vertice/subd/deployd/service.go:77 +0x17f
Mar 07 10:06:40 vds0 systemd[1]: virtengine.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 07 10:06:40 vds0 systemd[1]: virtengine.service: Unit entered failed state.
Mar 07 10:06:40 vds0 systemd[1]: virtengine.service: Failed with result 'exit-code'.

**Comment by vijaykanthm28** [comment]
issue fixed
